Add -G to getinfo

diff --git a/bin/getinfo b/bin/getinfo
--- a/bin/getinfo
+++ b/bin/getinfo
@@ -23,15 +23,34 @@
 ##:
 #h: Usage: getinfo ...
 #h:
-#h: Load shell scripts to fetch variables/configuration.
+#h: Load shell scripts to fetch and check variables/configurations in
+#h: shell scripts.
 #h:
-#h:   -l FILE...     : Load files.
-#h:   -L FILE...     : Load files (optional).
-#h:   -c VAR...      : Check variables are set, print VAR_help if not.
-#h:   -a VAR=HELP... : Set variable help.
-#h:   -p all|VARS... : Print variables.
-#h:   -s             : Print variable help summary.
-#h:   -g VARS...     : Get variable value.
+#h: Loading files and fetching variables:
+#h:
+#h:   -l FILE... : Load files.
+#h:   -L FILE... : Load files (optional).
+#h:   -g VARS... : Get variable value.
+#h:   -G VARS... : Get variable value trimed and '#' comments removed.
+#h:
+#h: Documenting variables:
+#h:
+#h:   -a VAR=HELP...   : Set variable help.
+#h:   -s               : Print variable help summary.
+#h:   -p all|VARS...   : Print variables and their values.
+#h:
+#h: Checking variables:
+#h:
+#h:   -c VAR[=CHECKER] : Check variables (By default whether set).
+#h:
+#h: The following checkers are defined:
+#h:
+#h:   s  : Is not empty.             yn : Can be "y" or "n".
+#h:   d  : Contains a directory.     f  : Contains a file.
+#h:
+#h: New checkers can be defined by creating functions/scripts with
+#h: the following interface: getinfo_c_NAME VARIABLE VALUE, which
+#h: return 1 and an error message in case of error.
 ##:
 getinfo() {
     local cmd="-g"
@@ -47,6 +66,7 @@ getinfo() {
             -a) getinfo_set_help        "$1";;
             -p) getinfo_print           "$1";;
             -g) getinfo_get             "$1";;
+            -G) getinfo_get_clean       "$1";;
             *)  echo >&2 "error: ${cmd}: Unsupported argument."; return 1;;
         esac
         shift
@@ -73,13 +93,16 @@ getinfo_load() {
     cd "${pwd}"
 }
 getinfo_check() {
-    if test -n "$(getinfo_get "$1")"; then
-        return 0
-    fi
-    local hlp="$(getinfo_get "${1}_help")"
-    echo >&2 "error: ${1}: Variable not set."
-    if test -n "${hlp}"; then
-        echo >&2 "error: ${1}: help: ${hlp}"
+    local var chk val hlp
+    case "$1" in
+        *=*) var="${1%%=*}" chk="${1#*=}";;
+        *)   var="${1}"     chk="s";;
+    esac
+    val="$(getinfo_get "${var}")"
+    if ! getinfo_c_"${chk}" "${var}" "${val}"; then
+        hlp="$(getinfo_get "${var}_help")"
+        test ! -n "${hlp}" || echo >&2 "error: ${var}: ${hlp}"
+        return 1
     fi
 }
 getinfo_set_help() {
@@ -91,11 +114,14 @@ getinfo_set_help() {
 getinfo_print() {
     local v
     if test @"$1" = @"all"; then
+        echo "____________________________________________________________________________________"
+        echo ""
         for v in ${GETINFO_VARS}; do
             getinfo_print "$v"
         done
+        echo "____________________________________________________________________________________"
     else
-        printf '%-30s : %s\n' "$1" "$(getinfo_get "$1")"
+        printf '%-30s : %s\n' "$1" "$(getinfo_get "$1" | sed '2,$s|^|    |')"
     fi
 }
 getinfo_print_summary() {
@@ -105,7 +131,55 @@ getinfo_print_summary() {
     done
 }
 getinfo_get() {
-    eval "echo \"\${$1}\""
+    local var
+    case "$1" in
+        *=*) var="${1%%=*}"; getinfo_check "$1";;
+        *)   var="${1}";;
+    esac
+    eval "echo \"\${$var}\""
+}
+getinfo_get_clean() {
+    getinfo_get "$1" | sed '
+    1{
+        /^ *$/d
+    }
+    ${
+        /^ *$/d
+    }
+    /^\#/{
+        d
+    }
+    '
+}
+
+## -------------------------------------------------------------------
+getinfo_c_s() { # NAME VALUE
+    if test ! -n "$2"; then
+        echo >&2 "error: $1: Variable not set."
+        return 1
+    fi
+}
+getinfo_c_d() { # NAME VALUE
+    if ! getinfo_c_s "$@"; then
+        return 1
+    elif test ! -d "$2"; then
+        echo >&2 "error: $1=$2: Not a directory."
+        return 1
+    fi
+}
+getinfo_c_f() { # NAME VALUE
+    if ! getinfo_c_s "$@"; then
+        return 1
+    elif test ! -f "$2"; then
+        echo >&2 "error: $1=$2: Not a file."
+        return 1
+    fi
+}
+getinfo_c_yn() { # NAME VALUE
+    case "$2" in
+        y|n) return 0;;
+        *)   echo >&2 "error: $1: Should be 'y' or 'n'."; return 1;;
+    esac
 }
 ## -------------------------------------------------------------------
 if test @"${SCRNAME:-$(basename "$0")}" = @"getinfo"; then
